### ISSUE TITLE
'Frozen executable' for Mac

### ISSUE THREAD

**Issue by kanavasait** [fzumstein/python-for-excel#2]
Hi, I am a Hardware Engineer exploring python to automate scrips. I have followed your book to develop a python tool using Excel. It was incredibly helpful. Now I want to share this tool across my team. But I am stuck because there is no 'Frozen executable' support for Mac in Xlwings module. Is there any other alternatives? I would really appreciate your suggestion

**Comment by fzumstein** [comment]
Hi @kanavasait, thanks for reading the book and so glad that you found it helpful! Somebody looked into this topic in https://github.com/xlwings/xlwings/issues/1154. The thing that makes everything a bit more complicated on macOS is that it's much more locked down and you may need to put your executable into a specific directory and the user may need to unblock it from the system preferences, which is usually not a very good user experience.

An easier solution may be to instruct your users to install anaconda/miniconda and create a specific conda env. You can automate all this with a bash script.

It's basically the approach I took with the PRO version: a one-line Terminal command that will take care of installing a Python installation with all dependencies. You can get an idea (or even try it out) from this project here:
https://danguetta.github.io/xlkitlearn/ (scroll to "Installation instructions - Mac")
